export const routes = {
    HOME: '/',
    LOGIN: '/login',
    ALBUM_LIST: '/albums',
    ALBUM_VIEW: '/album/view/:id',
    ALBUM_EDIT: '/album/edit/:id',
    ALBUM_CREATE: '/album/create',
    ALBUM_REVIEWS: '/album/reviews/:id',
    ALBUM_CATEGORIES: '/album/categories',
    SAMPLE_CATEGORIES: '/generator/sample/categories',
    SAMPLE_CREATE: '/generator/sample/create',
    SAMPLE_LIST: '/generator/sample/list',
    SAMPLE_VIEW: '/generator/sample/view/:id',
    SAMPLE_EDIT: '/generator/sample/edit/:id',
    SAMPLE_REVIEWS: '/generator/sample/reviews/:id',
    PRESET_CATEGORIES: '/generator/preset/categories',
    PRESET_CREATE: '/generator/preset/create',
    PRESET_LIST: '/generator/preset/list',
    PRESET_VIEW: '/generator/preset/view/:id',
    PRESET_EDIT: '/generator/preset/edit/:id',
    PRESET_REVIEWS: '/generator/preset/reviews/:id',
};
